### ISSUE TITLE
bug with 'follow' graphic when not logged in

### ISSUE THREAD

**Issue by behang** [mtuckerb/farkwar#14]
Tucker, when I click on a boat to follow when not logged in, a blank box shows on mouseover of the switch. See screenshot
![follow](https://cloud.githubusercontent.com/assets/4154086/3187058/06cd02ce-ecac-11e3-9fd2-9897d4b0c9ec.jpg)

**Comment by mtuckerb** [comment]
Okay, I think I've got this one fixed; at least to the letter of the original bug. If you think a different process (for non-boatie people) would be better, let's put it in a new ticket!
