### ISSUE TITLE
feature request: position report data presentation

### ISSUE THREAD

**Issue by behang** [mtuckerb/farkwar#18]
After spending time shuttling between keelscape and farkwar the last few days, checking up on boats we know, something I really like about keelscape is that I can see position while scanning a series of update reports on the same page. I find that I check the boats on the IO passage only every few days and really like that easy lookback to read the evolution of daily reports on sea state etc on their passage. It's not the end of the world to click on one pin after another to see that in farkwar, but it's more clicking around, and... well I guess I like less clicking around. You could put this on a separate page (like 'my waypoints' where I can see my data), but single page seems to me to be the better ux?

**Comment by mtuckerb** [comment]
Check out the new waypoints page and let me know if this doesn't address your suggestion!

**Comment by behang** [comment]
I think I confused this and #19. But, I'm also just not seeing it? Boat page looks the same. The only way I get to historical data is farkwar.com/waypoints, but chrono from oldest of all boats is awkward to navigate.

**Comment by mtuckerb** [comment]
You really  have to use the search and sort fields at this point, but it's
incredibly powerful. I can make shortcut buttons for each boat soon.
