### ISSUE TITLE
suggestion: clarify most recent position

### ISSUE THREAD

**Issue by behang** [mtuckerb/farkwar#19]
Our default map shows a cluster of positions. I've discovered, as we sit parked here for a few months, that people have consistently assumed we are in Singapore- pin kind of on the right hand side- when actually, we're in one of the cluster of positions to the left. Point being, there's no easy way to see what our last position actually is. possibilities:
- color code last position? most recent pin in cobalt blue, balance in red?
- add date info to data on pin click? (assume this can be pulled automatically in position update email; still requires user to click around and does not just make obvious which is most recent)
- date / update data could be noted in table of position report data below map?

**Comment by mtuckerb** [comment]
I've added an index to the pins, which might help a bit. I'm thinking of having a button to allow track view, which would make this more clear too!

**Comment by behang** [comment]
I'm not sure I'm finding this index. Do you mean this?
http://farkwar.com/waypoints
I think I'm finding that a little confusing, looks like a data dump of all boats in chronological order? If my goal is to get a specific waypoint for a specific boat, it gets me there eventually, but not a shortcut. Most likely scenario is to get recent waypoints for a boat. Keelscape UX makes a lot more sense for me there: single page, most recent on top, reference to pin on map. What it doesn't do is let me readily look back a half dozen waypoints and see what that position was- only the most recent is pinned on the map.
http://www.keelscape.com/vessel/key/ahBzfnNlY3JldC1iYXktNTcwchoLEgVPd25lchiBz7MCDAsSBlZlc3NlbBgBDA

**Comment by mtuckerb** [comment]
Ok, this is cleared up now. On the Boat page there is a list of the last 10 waypoints. Clicking on the target icon for any waypoint will zoom you to that pin on the map.
