### ISSUE TITLE
Super long lat/lon reports

### ISSUE THREAD

**Issue by shindigsailing** [mtuckerb/farkwar#21]
When email and facebook reports are sent positions are super long.
There is some type of conversion happening.

Example:

Moontide  just checked in.

Their position was  15.768500000000000000333333333 -96.096833333333333333.

They are currently    nautical miles from their destination ( Paraiso, Barra de Navidad and south).

**Comment by mikersanderson** [comment]
In addition to the super long positions, it would be nice to have them reported as a link, so that when you click on it, it will open the farkwar website at their location.  By the way Rob, Holly and I are in the Caribbean now!  The canal transit was a blast.

**Comment by mtuckerb** [comment]
Yeah, I know. It's just the decimal position rather than dd mm ss or did
mm.ss like you are used to. I'll probably be changing that in the next few
weeks, as a few people have complained.

**Comment by mikersanderson** [comment]
Let me know if you'd like some help on this … Holly and I are sailing full time, but in a past life, I was a software engineer ...

**Comment by mtuckerb** [comment]
All done! Thanks for the suggestions!
