### ISSUE TITLE
Sometimes the destination information disappears

### ISSUE THREAD

**Issue by shindigsailing** [mtuckerb/farkwar#22]
After entering a destination in the boat info it disappears after some time.  Distance to destination also goes away.

In my case this happened using Zihuatanejo, Mexico as a destination.

**Comment by mtuckerb** [comment]
Interesting. I have a feeling this is a problem with the mail parser. The parser looks for a Destination: <place name> and replaces the destination with what it finds. It may be triggering on something else. Do you find that this happens after a mailed in position report? Can you keep an eye on it for me?

With distance to destination, we use Google Map's free tier. I get something like 5000 requests a day, which (believe it or not) we go through. This messes with all the calculations. I'm thinking of taking donation to cover costs, and one of those would be upgrading to a paid tier for the Google API.

**Comment by mtuckerb** [comment]
I found the bug. It seems I was expecting the Destination to be set in /every/ message. That's not what we were after so I've changed it to only set the destination if one is given. Thanks for bringing it to my attention!
