### ISSUE TITLE
Feature Request: derive mileage and speed between reported positions

### ISSUE THREAD

**Issue by jaffadog** [mtuckerb/farkwar#27]
Hi Tucker - really digging Farkwar.  And the name.  So many possible meanings.  But I digress.  In the waypoints lists, it would be cool if you could display the derived straight-line distance and average speed from the previous reported waypoint.

**Comment by mtuckerb** [comment]
https://github.com/kristianmandrup/haversine

**Comment by mtuckerb** [comment]
Resolved a long long time ago, but forgot to close the issue. :(
