### ISSUE TITLE
Facebook reporting lots of extra digits

### ISSUE THREAD

**Issue by shindigsailing** [mtuckerb/farkwar#28]
I entered the following through a sailmail post: 

At 05/10/2015 13:36 (utc) our position was 25°49.29'N 111°18.67'W 

On facebook it was posted as Shindig is at 25.821500000000000000333333333 -111.311166666666666666666666667

**Comment by mtuckerb** [comment]
Ah yes, the high precision decimal degrees position.. I recently changed
all of these to the pretty format but must have missed a few. I'll fix that
soon!
Cheers,
-=Tucker

**Comment by mtuckerb** [comment]
fixed
